### ISSUE TITLE
Bug: Transfer Functions Hangs

### ISSUE THREAD

**Issue by insp3ctre** [benhg/blt-funcx-toolkit#2]
Either function from the transfer module hangs. 

This keeps me from transferring files between BLT. It is unclear if this issue is with funcx or with our code. 

To reproduce, try running an upload or download function, and it will hang.

**Comment by benhg** [comment]
Debugging in progress

**Comment by benhg** [comment]
Debugging complete. Turned out to be caused by a version mismatch between python versions on laptop and BLT. Will report this to the FuncX team so they can pin the versions.
